name: CI Run

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn
    - run: yarn prettier
    - run: yarn lint
    - run: yarn test --coverage
    - name: Upload to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage/
        files: ./clover.xml
        flags: unittests
        name: codecov-report
        verbose: true
    - run: yarn build