name: blui-pr-actions

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - '*/*'

permissions:
  pull-requests: write
  contents: read

jobs:
  pr-labels:
    uses: etn-ccis/blui-automation/.github/workflows/blui-labels.yml@dev
    secrets: inherit

  pr-comment:
    uses: etn-ccis/blui-automation/.github/workflows/blui-comment.yml@dev
    secrets: inherit